def average_value(a,b,c):
    return((a+b+c)/3)
print("fun calculator of doom")
a = input("Enter a number: ")
b = input("Enter a number: ")
c = input("Enter a number: ")
a = int(a)
b = int(b)
c = int(c)
print("The average of the three numbers is: ", average_value(a,b,c))